<?php

namespace Disclaimer\Providers;

class DisclaimerFieldsServiceProvider implements Provider
{
    public function __construct()
    {
        add_action('acf/init', [$this, 'acf_disclaimer_fields']);
        add_filter('acf/load_field/key=field_disclaimer_posts_settings_user_types_allow', [$this, 'acf_disclaimer_load_user_types']);
    }

    public function register()
    {
        //
    }

    public function acf_disclaimer_load_user_types($field) {
        if(is_admin()) {
            $field['choices'] = array();
            $users = get_field('disclaimer_settings_user_types', 'option');
            $usersArrays = [];
            foreach($users as $user) {
                $usersArrays[\Disclaimer\disclaimerReplaceAll($user['disclaimer_settings_user_types_name'])] = $user['disclaimer_settings_user_types_name'];
            }
            $field['choices'] = $usersArrays;
        }
        return $field;
    }

    public function acf_disclaimer_fields() {
        if (!function_exists('acf_add_options_page')) {
            return;
        }

        acf_add_local_field_group(array(
            'key'   => 'group_disclaimer_settings',
            'title' => 'Disclaimer Settings',
            'fields'    => array (),
            'position'  => 'acf_after_title',
            'menu_order'    => 0,
            'label_placement'   => 'top',
            'style' => 'default',
            'active'    => true,
            'description'   => '',
            'location'  => array (
                array (
                    array (
                        'param' => 'options_page',
                        'operator'  => '==',
                        'value' => 'acf-options-disclaimer-settings',
                    ),
                ),
            ),
        ));
        
        acf_add_local_field(array(
            'key'   => 'field_disclaimer_settings_enable_disclaimer',
            'label' => 'Enable disclaimer?',
            'name'  => 'disclaimer_settings_enable_disclaimer',
            'type'  => 'true_false',
            'required' => 0,
            'default_value' => 0,
            'ui' => 1,
            'parent' => 'group_disclaimer_settings',
        ));

        acf_add_local_field(array(
            'key'   => 'field_disclaimer_settings_heading',
            'label' => 'Heading',
            'name'  => 'disclaimer_settings_heading',
            'type'  => 'text',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_disclaimer_settings_enable_disclaimer',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'parent' => 'group_disclaimer_settings',
        ));

        acf_add_local_field(array(
            'key'   => 'field_disclaimer_settings_content',
            'label' => 'Content',
            'name'  => 'disclaimer_settings_content',
            'type'  => 'wysiwyg',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_disclaimer_settings_enable_disclaimer',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 0,
            'delay' => 0,
            'parent' => 'group_disclaimer_settings',
        ));

        acf_add_local_field(array(
            'key'   => 'field_disclaimer_settings_show_country',
            'label' => 'Show country field?',
            'name'  => 'disclaimer_settings_show_country',
            'type'  => 'true_false',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_disclaimer_settings_enable_disclaimer',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'default_value' => 0,
            'ui' => 1,
            'parent' => 'group_disclaimer_settings',
        ));

        acf_add_local_field(array(
            'key'   => 'field_disclaimer_settings_countries_all',
            'label' => 'Show all countries?',
            'name'  => 'disclaimer_settings_countries_all',
            'type'  => 'true_false',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_disclaimer_settings_show_country',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'default_value' => 0,
            'ui' => 1,
            'parent' => 'group_disclaimer_settings',
        ));

        acf_add_local_field(array(
            'key'   => 'field_disclaimer_settings_countries',
            'label' => 'Countries',
            'name'  => 'disclaimer_settings_countries',
            'type'  => 'select',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_disclaimer_settings_show_country',
                        'operator' => '==',
                        'value' => '1',
                    ),
                    array(
                        'field' => 'field_disclaimer_settings_countries_all',
                        'operator' => '==',
                        'value' => '0',
                    ),
                ),
            ),
            'choices' => array(
                'AF' => 'Afghanistan',
                'AX' => 'Åland Islands',
                'AL' => 'Albania',
                'DZ' => 'Algeria',
                'AS' => 'American Samoa',
                'AD' => 'Andorra',
                'AO' => 'Angola',
                'AI' => 'Anguilla',
                'AQ' => 'Antarctica',
                'AG' => 'Antigua & Barbuda',
                'AR' => 'Argentina',
                'AM' => 'Armenia',
                'AW' => 'Aruba',
                'AC' => 'Ascension Island',
                'AU' => 'Australia',
                'AT' => 'Austria',
                'AZ' => 'Azerbaijan',
                'BS' => 'Bahamas',
                'BH' => 'Bahrain',
                'BD' => 'Bangladesh',
                'BB' => 'Barbados',
                'BY' => 'Belarus',
                'BE' => 'Belgium',
                'BZ' => 'Belize',
                'BJ' => 'Benin',
                'BM' => 'Bermuda',
                'BT' => 'Bhutan',
                'BO' => 'Bolivia',
                'BA' => 'Bosnia & Herzegovina',
                'BW' => 'Botswana',
                'BR' => 'Brazil',
                'IO' => 'British Indian Ocean Territory',
                'VG' => 'British Virgin Islands',
                'BN' => 'Brunei',
                'BG' => 'Bulgaria',
                'BF' => 'Burkina Faso',
                'BI' => 'Burundi',
                'KH' => 'Cambodia',
                'CM' => 'Cameroon',
                'CA' => 'Canada',
                'IC' => 'Canary Islands',
                'CV' => 'Cape Verde',
                'BQ' => 'Caribbean Netherlands',
                'KY' => 'Cayman Islands',
                'CF' => 'Central African Republic',
                'EA' => 'Ceuta & Melilla',
                'TD' => 'Chad',
                'CL' => 'Chile',
                'CN' => 'China',
                'CX' => 'Christmas Island',
                'CC' => 'Cocos (Keeling) Islands',
                'CO' => 'Colombia',
                'KM' => 'Comoros',
                'CG' => 'Congo - Brazzaville',
                'CD' => 'Congo - Kinshasa',
                'CK' => 'Cook Islands',
                'CR' => 'Costa Rica',
                'CI' => 'Côte d’Ivoire',
                'HR' => 'Croatia',
                'CU' => 'Cuba',
                'CW' => 'Curaçao',
                'CY' => 'Cyprus',
                'CZ' => 'Czechia',
                'DK' => 'Denmark',
                'DG' => 'Diego Garcia',
                'DJ' => 'Djibouti',
                'DM' => 'Dominica',
                'DO' => 'Dominican Republic',
                'EC' => 'Ecuador',
                'EG' => 'Egypt',
                'SV' => 'El Salvador',
                'GQ' => 'Equatorial Guinea',
                'ER' => 'Eritrea',
                'EE' => 'Estonia',
                'SZ' => 'Eswatini',
                'ET' => 'Ethiopia',
                'FK' => 'Falkland Islands',
                'FO' => 'Faroe Islands',
                'FJ' => 'Fiji',
                'FI' => 'Finland',
                'FR' => 'France',
                'GF' => 'French Guiana',
                'PF' => 'French Polynesia',
                'TF' => 'French Southern Territories',
                'GA' => 'Gabon',
                'GM' => 'Gambia',
                'GE' => 'Georgia',
                'DE' => 'Germany',
                'GH' => 'Ghana',
                'GI' => 'Gibraltar',
                'GR' => 'Greece',
                'GL' => 'Greenland',
                'GD' => 'Grenada',
                'GP' => 'Guadeloupe',
                'GU' => 'Guam',
                'GT' => 'Guatemala',
                'GG' => 'Guernsey',
                'GN' => 'Guinea',
                'GW' => 'Guinea-Bissau',
                'GY' => 'Guyana',
                'HT' => 'Haiti',
                'HN' => 'Honduras',
                'HK' => 'Hong Kong SAR China',
                'HU' => 'Hungary',
                'IS' => 'Iceland',
                'IN' => 'India',
                'ID' => 'Indonesia',
                'IR' => 'Iran',
                'IQ' => 'Iraq',
                'IE' => 'Ireland',
                'IM' => 'Isle of Man',
                'IL' => 'Israel',
                'IT' => 'Italy',
                'JM' => 'Jamaica',
                'JP' => 'Japan',
                'JE' => 'Jersey',
                'JO' => 'Jordan',
                'KZ' => 'Kazakhstan',
                'KE' => 'Kenya',
                'KI' => 'Kiribati',
                'XK' => 'Kosovo',
                'KW' => 'Kuwait',
                'KG' => 'Kyrgyzstan',
                'LA' => 'Laos',
                'LV' => 'Latvia',
                'LB' => 'Lebanon',
                'LS' => 'Lesotho',
                'LR' => 'Liberia',
                'LY' => 'Libya',
                'LI' => 'Liechtenstein',
                'LT' => 'Lithuania',
                'LU' => 'Luxembourg',
                'MO' => 'Macao SAR China',
                'MG' => 'Madagascar',
                'MW' => 'Malawi',
                'MY' => 'Malaysia',
                'MV' => 'Maldives',
                'ML' => 'Mali',
                'MT' => 'Malta',
                'MH' => 'Marshall Islands',
                'MQ' => 'Martinique',
                'MR' => 'Mauritania',
                'MU' => 'Mauritius',
                'YT' => 'Mayotte',
                'MX' => 'Mexico',
                'FM' => 'Micronesia',
                'MD' => 'Moldova',
                'MC' => 'Monaco',
                'MN' => 'Mongolia',
                'ME' => 'Montenegro',
                'MS' => 'Montserrat',
                'MA' => 'Morocco',
                'MZ' => 'Mozambique',
                'MM' => 'Myanmar (Burma)',
                'NA' => 'Namibia',
                'NR' => 'Nauru',
                'NP' => 'Nepal',
                'NL' => 'Netherlands',
                'NC' => 'New Caledonia',
                'NZ' => 'New Zealand',
                'NI' => 'Nicaragua',
                'NE' => 'Niger',
                'NG' => 'Nigeria',
                'NU' => 'Niue',
                'NF' => 'Norfolk Island',
                'KP' => 'North Korea',
                'MK' => 'North Macedonia',
                'MP' => 'Northern Mariana Islands',
                'NO' => 'Norway',
                'OM' => 'Oman',
                'PK' => 'Pakistan',
                'PW' => 'Palau',
                'PS' => 'Palestinian Territories',
                'PA' => 'Panama',
                'PG' => 'Papua New Guinea',
                'PY' => 'Paraguay',
                'PE' => 'Peru',
                'PH' => 'Philippines',
                'PN' => 'Pitcairn Islands',
                'PL' => 'Poland',
                'PT' => 'Portugal',
                'XA' => 'Pseudo-Accents',
                'XB' => 'Pseudo-Bidi',
                'PR' => 'Puerto Rico',
                'QA' => 'Qatar',
                'RE' => 'Réunion',
                'RO' => 'Romania',
                'RU' => 'Russia',
                'RW' => 'Rwanda',
                'WS' => 'Samoa',
                'SM' => 'San Marino',
                'ST' => 'São Tomé & Príncipe',
                'SA' => 'Saudi Arabia',
                'SN' => 'Senegal',
                'RS' => 'Serbia',
                'SC' => 'Seychelles',
                'SL' => 'Sierra Leone',
                'SG' => 'Singapore',
                'SX' => 'Sint Maarten',
                'SK' => 'Slovakia',
                'SI' => 'Slovenia',
                'SB' => 'Solomon Islands',
                'SO' => 'Somalia',
                'ZA' => 'South Africa',
                'GS' => 'South Georgia & South Sandwich Islands',
                'KR' => 'South Korea',
                'SS' => 'South Sudan',
                'ES' => 'Spain',
                'LK' => 'Sri Lanka',
                'BL' => 'St Barthélemy',
                'SH' => 'St Helena',
                'KN' => 'St Kitts & Nevis',
                'LC' => 'St Lucia',
                'MF' => 'St Martin',
                'PM' => 'St Pierre & Miquelon',
                'VC' => 'St Vincent & Grenadines',
                'SD' => 'Sudan',
                'SR' => 'Suriname',
                'SJ' => 'Svalbard & Jan Mayen',
                'SE' => 'Sweden',
                'CH' => 'Switzerland',
                'SY' => 'Syria',
                'TW' => 'Taiwan',
                'TJ' => 'Tajikistan',
                'TZ' => 'Tanzania',
                'TH' => 'Thailand',
                'TL' => 'Timor-Leste',
                'TG' => 'Togo',
                'TK' => 'Tokelau',
                'TO' => 'Tonga',
                'TT' => 'Trinidad & Tobago',
                'TA' => 'Tristan da Cunha',
                'TN' => 'Tunisia',
                'TR' => 'Turkey',
                'TM' => 'Turkmenistan',
                'TC' => 'Turks & Caicos Islands',
                'TV' => 'Tuvalu',
                'UG' => 'Uganda',
                'UA' => 'Ukraine',
                'AE' => 'United Arab Emirates',
                'GB' => 'United Kingdom',
                'US' => 'United States',
                'UY' => 'Uruguay',
                'UM' => 'US Outlying Islands',
                'VI' => 'US Virgin Islands',
                'UZ' => 'Uzbekistan',
                'VU' => 'Vanuatu',
                'VA' => 'Vatican City',
                'VE' => 'Venezuela',
                'VN' => 'Vietnam',
                'WF' => 'Wallis & Futuna',
                'EH' => 'Western Sahara',
                'YE' => 'Yemen',
                'ZM' => 'Zambia',
                'ZW' => 'Zimbabwe',
            ),
            'placeholder' => 'Select a country',
            'default_value' => array(
            ),
            'allow_null' => 0,
            'multiple' => 1,
            'ui' => 1,
            'return_format' => 'array',
            'layout' => 'vertical',
            'ajax' => 0,
            'parent' => 'group_disclaimer_settings',
        ));

        acf_add_local_field(array(
            'key'   => 'field_disclaimer_settings_countries_to_allow',
            'label' => 'Countries to allow',
            'name'  => 'disclaimer_settings_countries_to_allow',
            'type'  => 'select',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_disclaimer_settings_show_country',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'choices' => array(
                'AF' => 'Afghanistan',
                'AX' => 'Åland Islands',
                'AL' => 'Albania',
                'DZ' => 'Algeria',
                'AS' => 'American Samoa',
                'AD' => 'Andorra',
                'AO' => 'Angola',
                'AI' => 'Anguilla',
                'AQ' => 'Antarctica',
                'AG' => 'Antigua & Barbuda',
                'AR' => 'Argentina',
                'AM' => 'Armenia',
                'AW' => 'Aruba',
                'AC' => 'Ascension Island',
                'AU' => 'Australia',
                'AT' => 'Austria',
                'AZ' => 'Azerbaijan',
                'BS' => 'Bahamas',
                'BH' => 'Bahrain',
                'BD' => 'Bangladesh',
                'BB' => 'Barbados',
                'BY' => 'Belarus',
                'BE' => 'Belgium',
                'BZ' => 'Belize',
                'BJ' => 'Benin',
                'BM' => 'Bermuda',
                'BT' => 'Bhutan',
                'BO' => 'Bolivia',
                'BA' => 'Bosnia & Herzegovina',
                'BW' => 'Botswana',
                'BR' => 'Brazil',
                'IO' => 'British Indian Ocean Territory',
                'VG' => 'British Virgin Islands',
                'BN' => 'Brunei',
                'BG' => 'Bulgaria',
                'BF' => 'Burkina Faso',
                'BI' => 'Burundi',
                'KH' => 'Cambodia',
                'CM' => 'Cameroon',
                'CA' => 'Canada',
                'IC' => 'Canary Islands',
                'CV' => 'Cape Verde',
                'BQ' => 'Caribbean Netherlands',
                'KY' => 'Cayman Islands',
                'CF' => 'Central African Republic',
                'EA' => 'Ceuta & Melilla',
                'TD' => 'Chad',
                'CL' => 'Chile',
                'CN' => 'China',
                'CX' => 'Christmas Island',
                'CC' => 'Cocos (Keeling) Islands',
                'CO' => 'Colombia',
                'KM' => 'Comoros',
                'CG' => 'Congo - Brazzaville',
                'CD' => 'Congo - Kinshasa',
                'CK' => 'Cook Islands',
                'CR' => 'Costa Rica',
                'CI' => 'Côte d’Ivoire',
                'HR' => 'Croatia',
                'CU' => 'Cuba',
                'CW' => 'Curaçao',
                'CY' => 'Cyprus',
                'CZ' => 'Czechia',
                'DK' => 'Denmark',
                'DG' => 'Diego Garcia',
                'DJ' => 'Djibouti',
                'DM' => 'Dominica',
                'DO' => 'Dominican Republic',
                'EC' => 'Ecuador',
                'EG' => 'Egypt',
                'SV' => 'El Salvador',
                'GQ' => 'Equatorial Guinea',
                'ER' => 'Eritrea',
                'EE' => 'Estonia',
                'SZ' => 'Eswatini',
                'ET' => 'Ethiopia',
                'FK' => 'Falkland Islands',
                'FO' => 'Faroe Islands',
                'FJ' => 'Fiji',
                'FI' => 'Finland',
                'FR' => 'France',
                'GF' => 'French Guiana',
                'PF' => 'French Polynesia',
                'TF' => 'French Southern Territories',
                'GA' => 'Gabon',
                'GM' => 'Gambia',
                'GE' => 'Georgia',
                'DE' => 'Germany',
                'GH' => 'Ghana',
                'GI' => 'Gibraltar',
                'GR' => 'Greece',
                'GL' => 'Greenland',
                'GD' => 'Grenada',
                'GP' => 'Guadeloupe',
                'GU' => 'Guam',
                'GT' => 'Guatemala',
                'GG' => 'Guernsey',
                'GN' => 'Guinea',
                'GW' => 'Guinea-Bissau',
                'GY' => 'Guyana',
                'HT' => 'Haiti',
                'HN' => 'Honduras',
                'HK' => 'Hong Kong SAR China',
                'HU' => 'Hungary',
                'IS' => 'Iceland',
                'IN' => 'India',
                'ID' => 'Indonesia',
                'IR' => 'Iran',
                'IQ' => 'Iraq',
                'IE' => 'Ireland',
                'IM' => 'Isle of Man',
                'IL' => 'Israel',
                'IT' => 'Italy',
                'JM' => 'Jamaica',
                'JP' => 'Japan',
                'JE' => 'Jersey',
                'JO' => 'Jordan',
                'KZ' => 'Kazakhstan',
                'KE' => 'Kenya',
                'KI' => 'Kiribati',
                'XK' => 'Kosovo',
                'KW' => 'Kuwait',
                'KG' => 'Kyrgyzstan',
                'LA' => 'Laos',
                'LV' => 'Latvia',
                'LB' => 'Lebanon',
                'LS' => 'Lesotho',
                'LR' => 'Liberia',
                'LY' => 'Libya',
                'LI' => 'Liechtenstein',
                'LT' => 'Lithuania',
                'LU' => 'Luxembourg',
                'MO' => 'Macao SAR China',
                'MG' => 'Madagascar',
                'MW' => 'Malawi',
                'MY' => 'Malaysia',
                'MV' => 'Maldives',
                'ML' => 'Mali',
                'MT' => 'Malta',
                'MH' => 'Marshall Islands',
                'MQ' => 'Martinique',
                'MR' => 'Mauritania',
                'MU' => 'Mauritius',
                'YT' => 'Mayotte',
                'MX' => 'Mexico',
                'FM' => 'Micronesia',
                'MD' => 'Moldova',
                'MC' => 'Monaco',
                'MN' => 'Mongolia',
                'ME' => 'Montenegro',
                'MS' => 'Montserrat',
                'MA' => 'Morocco',
                'MZ' => 'Mozambique',
                'MM' => 'Myanmar (Burma)',
                'NA' => 'Namibia',
                'NR' => 'Nauru',
                'NP' => 'Nepal',
                'NL' => 'Netherlands',
                'NC' => 'New Caledonia',
                'NZ' => 'New Zealand',
                'NI' => 'Nicaragua',
                'NE' => 'Niger',
                'NG' => 'Nigeria',
                'NU' => 'Niue',
                'NF' => 'Norfolk Island',
                'KP' => 'North Korea',
                'MK' => 'North Macedonia',
                'MP' => 'Northern Mariana Islands',
                'NO' => 'Norway',
                'OM' => 'Oman',
                'PK' => 'Pakistan',
                'PW' => 'Palau',
                'PS' => 'Palestinian Territories',
                'PA' => 'Panama',
                'PG' => 'Papua New Guinea',
                'PY' => 'Paraguay',
                'PE' => 'Peru',
                'PH' => 'Philippines',
                'PN' => 'Pitcairn Islands',
                'PL' => 'Poland',
                'PT' => 'Portugal',
                'XA' => 'Pseudo-Accents',
                'XB' => 'Pseudo-Bidi',
                'PR' => 'Puerto Rico',
                'QA' => 'Qatar',
                'RE' => 'Réunion',
                'RO' => 'Romania',
                'RU' => 'Russia',
                'RW' => 'Rwanda',
                'WS' => 'Samoa',
                'SM' => 'San Marino',
                'ST' => 'São Tomé & Príncipe',
                'SA' => 'Saudi Arabia',
                'SN' => 'Senegal',
                'RS' => 'Serbia',
                'SC' => 'Seychelles',
                'SL' => 'Sierra Leone',
                'SG' => 'Singapore',
                'SX' => 'Sint Maarten',
                'SK' => 'Slovakia',
                'SI' => 'Slovenia',
                'SB' => 'Solomon Islands',
                'SO' => 'Somalia',
                'ZA' => 'South Africa',
                'GS' => 'South Georgia & South Sandwich Islands',
                'KR' => 'South Korea',
                'SS' => 'South Sudan',
                'ES' => 'Spain',
                'LK' => 'Sri Lanka',
                'BL' => 'St Barthélemy',
                'SH' => 'St Helena',
                'KN' => 'St Kitts & Nevis',
                'LC' => 'St Lucia',
                'MF' => 'St Martin',
                'PM' => 'St Pierre & Miquelon',
                'VC' => 'St Vincent & Grenadines',
                'SD' => 'Sudan',
                'SR' => 'Suriname',
                'SJ' => 'Svalbard & Jan Mayen',
                'SE' => 'Sweden',
                'CH' => 'Switzerland',
                'SY' => 'Syria',
                'TW' => 'Taiwan',
                'TJ' => 'Tajikistan',
                'TZ' => 'Tanzania',
                'TH' => 'Thailand',
                'TL' => 'Timor-Leste',
                'TG' => 'Togo',
                'TK' => 'Tokelau',
                'TO' => 'Tonga',
                'TT' => 'Trinidad & Tobago',
                'TA' => 'Tristan da Cunha',
                'TN' => 'Tunisia',
                'TR' => 'Turkey',
                'TM' => 'Turkmenistan',
                'TC' => 'Turks & Caicos Islands',
                'TV' => 'Tuvalu',
                'UG' => 'Uganda',
                'UA' => 'Ukraine',
                'AE' => 'United Arab Emirates',
                'GB' => 'United Kingdom',
                'US' => 'United States',
                'UY' => 'Uruguay',
                'UM' => 'US Outlying Islands',
                'VI' => 'US Virgin Islands',
                'UZ' => 'Uzbekistan',
                'VU' => 'Vanuatu',
                'VA' => 'Vatican City',
                'VE' => 'Venezuela',
                'VN' => 'Vietnam',
                'WF' => 'Wallis & Futuna',
                'EH' => 'Western Sahara',
                'YE' => 'Yemen',
                'ZM' => 'Zambia',
                'ZW' => 'Zimbabwe',
            ),
            'placeholder' => 'Select countries',
            'default_value' => array(
            ),
            'allow_null' => 0,
            'multiple' => 1,
            'ui' => 1,
            'return_format' => 'array',
            'layout' => 'vertical',
            'ajax' => 0,
            'parent' => 'group_disclaimer_settings',
        ));

        acf_add_local_field(array(
            'key'   => 'field_disclaimer_settings_country_disclaimers',
            'label' => 'Country disclaimers',
            'name'  => 'disclaimer_settings_country_disclaimers',
            'type'  => 'repeater',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_disclaimer_settings_show_country',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => 'Add Country Disclaimer',
            'rows_per_page' => 20,
            'parent' => 'group_disclaimer_settings',
            'sub_field' => array(),
        ));

            acf_add_local_field(array(
                'key'   => 'field_disclaimer_settings_country_disclaimers_group',
                'label' => 'Group',
                'name'  => 'disclaimer_settings_country_disclaimers_group',
                'type'  => 'group',
                'required' => 0,
                'layout' => 'block',
                'sub_field' => array(),
                'parent' => 'field_disclaimer_settings_country_disclaimers',
            ));

                acf_add_local_field(array(
                    'key'   => 'field_disclaimer_settings_country_disclaimers_group_countries',
                    'label' => 'Countries',
                    'name'  => 'disclaimer_settings_country_disclaimers_group_countries',
                    'type'  => 'select',
                    'required' => 0,
                    'choices' => array(
                        'AF' => 'Afghanistan',
                        'AX' => 'Åland Islands',
                        'AL' => 'Albania',
                        'DZ' => 'Algeria',
                        'AS' => 'American Samoa',
                        'AD' => 'Andorra',
                        'AO' => 'Angola',
                        'AI' => 'Anguilla',
                        'AQ' => 'Antarctica',
                        'AG' => 'Antigua & Barbuda',
                        'AR' => 'Argentina',
                        'AM' => 'Armenia',
                        'AW' => 'Aruba',
                        'AC' => 'Ascension Island',
                        'AU' => 'Australia',
                        'AT' => 'Austria',
                        'AZ' => 'Azerbaijan',
                        'BS' => 'Bahamas',
                        'BH' => 'Bahrain',
                        'BD' => 'Bangladesh',
                        'BB' => 'Barbados',
                        'BY' => 'Belarus',
                        'BE' => 'Belgium',
                        'BZ' => 'Belize',
                        'BJ' => 'Benin',
                        'BM' => 'Bermuda',
                        'BT' => 'Bhutan',
                        'BO' => 'Bolivia',
                        'BA' => 'Bosnia & Herzegovina',
                        'BW' => 'Botswana',
                        'BR' => 'Brazil',
                        'IO' => 'British Indian Ocean Territory',
                        'VG' => 'British Virgin Islands',
                        'BN' => 'Brunei',
                        'BG' => 'Bulgaria',
                        'BF' => 'Burkina Faso',
                        'BI' => 'Burundi',
                        'KH' => 'Cambodia',
                        'CM' => 'Cameroon',
                        'CA' => 'Canada',
                        'IC' => 'Canary Islands',
                        'CV' => 'Cape Verde',
                        'BQ' => 'Caribbean Netherlands',
                        'KY' => 'Cayman Islands',
                        'CF' => 'Central African Republic',
                        'EA' => 'Ceuta & Melilla',
                        'TD' => 'Chad',
                        'CL' => 'Chile',
                        'CN' => 'China',
                        'CX' => 'Christmas Island',
                        'CC' => 'Cocos (Keeling) Islands',
                        'CO' => 'Colombia',
                        'KM' => 'Comoros',
                        'CG' => 'Congo - Brazzaville',
                        'CD' => 'Congo - Kinshasa',
                        'CK' => 'Cook Islands',
                        'CR' => 'Costa Rica',
                        'CI' => 'Côte d’Ivoire',
                        'HR' => 'Croatia',
                        'CU' => 'Cuba',
                        'CW' => 'Curaçao',
                        'CY' => 'Cyprus',
                        'CZ' => 'Czechia',
                        'DK' => 'Denmark',
                        'DG' => 'Diego Garcia',
                        'DJ' => 'Djibouti',
                        'DM' => 'Dominica',
                        'DO' => 'Dominican Republic',
                        'EC' => 'Ecuador',
                        'EG' => 'Egypt',
                        'SV' => 'El Salvador',
                        'GQ' => 'Equatorial Guinea',
                        'ER' => 'Eritrea',
                        'EE' => 'Estonia',
                        'SZ' => 'Eswatini',
                        'ET' => 'Ethiopia',
                        'FK' => 'Falkland Islands',
                        'FO' => 'Faroe Islands',
                        'FJ' => 'Fiji',
                        'FI' => 'Finland',
                        'FR' => 'France',
                        'GF' => 'French Guiana',
                        'PF' => 'French Polynesia',
                        'TF' => 'French Southern Territories',
                        'GA' => 'Gabon',
                        'GM' => 'Gambia',
                        'GE' => 'Georgia',
                        'DE' => 'Germany',
                        'GH' => 'Ghana',
                        'GI' => 'Gibraltar',
                        'GR' => 'Greece',
                        'GL' => 'Greenland',
                        'GD' => 'Grenada',
                        'GP' => 'Guadeloupe',
                        'GU' => 'Guam',
                        'GT' => 'Guatemala',
                        'GG' => 'Guernsey',
                        'GN' => 'Guinea',
                        'GW' => 'Guinea-Bissau',
                        'GY' => 'Guyana',
                        'HT' => 'Haiti',
                        'HN' => 'Honduras',
                        'HK' => 'Hong Kong SAR China',
                        'HU' => 'Hungary',
                        'IS' => 'Iceland',
                        'IN' => 'India',
                        'ID' => 'Indonesia',
                        'IR' => 'Iran',
                        'IQ' => 'Iraq',
                        'IE' => 'Ireland',
                        'IM' => 'Isle of Man',
                        'IL' => 'Israel',
                        'IT' => 'Italy',
                        'JM' => 'Jamaica',
                        'JP' => 'Japan',
                        'JE' => 'Jersey',
                        'JO' => 'Jordan',
                        'KZ' => 'Kazakhstan',
                        'KE' => 'Kenya',
                        'KI' => 'Kiribati',
                        'XK' => 'Kosovo',
                        'KW' => 'Kuwait',
                        'KG' => 'Kyrgyzstan',
                        'LA' => 'Laos',
                        'LV' => 'Latvia',
                        'LB' => 'Lebanon',
                        'LS' => 'Lesotho',
                        'LR' => 'Liberia',
                        'LY' => 'Libya',
                        'LI' => 'Liechtenstein',
                        'LT' => 'Lithuania',
                        'LU' => 'Luxembourg',
                        'MO' => 'Macao SAR China',
                        'MG' => 'Madagascar',
                        'MW' => 'Malawi',
                        'MY' => 'Malaysia',
                        'MV' => 'Maldives',
                        'ML' => 'Mali',
                        'MT' => 'Malta',
                        'MH' => 'Marshall Islands',
                        'MQ' => 'Martinique',
                        'MR' => 'Mauritania',
                        'MU' => 'Mauritius',
                        'YT' => 'Mayotte',
                        'MX' => 'Mexico',
                        'FM' => 'Micronesia',
                        'MD' => 'Moldova',
                        'MC' => 'Monaco',
                        'MN' => 'Mongolia',
                        'ME' => 'Montenegro',
                        'MS' => 'Montserrat',
                        'MA' => 'Morocco',
                        'MZ' => 'Mozambique',
                        'MM' => 'Myanmar (Burma)',
                        'NA' => 'Namibia',
                        'NR' => 'Nauru',
                        'NP' => 'Nepal',
                        'NL' => 'Netherlands',
                        'NC' => 'New Caledonia',
                        'NZ' => 'New Zealand',
                        'NI' => 'Nicaragua',
                        'NE' => 'Niger',
                        'NG' => 'Nigeria',
                        'NU' => 'Niue',
                        'NF' => 'Norfolk Island',
                        'KP' => 'North Korea',
                        'MK' => 'North Macedonia',
                        'MP' => 'Northern Mariana Islands',
                        'NO' => 'Norway',
                        'OM' => 'Oman',
                        'PK' => 'Pakistan',
                        'PW' => 'Palau',
                        'PS' => 'Palestinian Territories',
                        'PA' => 'Panama',
                        'PG' => 'Papua New Guinea',
                        'PY' => 'Paraguay',
                        'PE' => 'Peru',
                        'PH' => 'Philippines',
                        'PN' => 'Pitcairn Islands',
                        'PL' => 'Poland',
                        'PT' => 'Portugal',
                        'XA' => 'Pseudo-Accents',
                        'XB' => 'Pseudo-Bidi',
                        'PR' => 'Puerto Rico',
                        'QA' => 'Qatar',
                        'RE' => 'Réunion',
                        'RO' => 'Romania',
                        'RU' => 'Russia',
                        'RW' => 'Rwanda',
                        'WS' => 'Samoa',
                        'SM' => 'San Marino',
                        'ST' => 'São Tomé & Príncipe',
                        'SA' => 'Saudi Arabia',
                        'SN' => 'Senegal',
                        'RS' => 'Serbia',
                        'SC' => 'Seychelles',
                        'SL' => 'Sierra Leone',
                        'SG' => 'Singapore',
                        'SX' => 'Sint Maarten',
                        'SK' => 'Slovakia',
                        'SI' => 'Slovenia',
                        'SB' => 'Solomon Islands',
                        'SO' => 'Somalia',
                        'ZA' => 'South Africa',
                        'GS' => 'South Georgia & South Sandwich Islands',
                        'KR' => 'South Korea',
                        'SS' => 'South Sudan',
                        'ES' => 'Spain',
                        'LK' => 'Sri Lanka',
                        'BL' => 'St Barthélemy',
                        'SH' => 'St Helena',
                        'KN' => 'St Kitts & Nevis',
                        'LC' => 'St Lucia',
                        'MF' => 'St Martin',
                        'PM' => 'St Pierre & Miquelon',
                        'VC' => 'St Vincent & Grenadines',
                        'SD' => 'Sudan',
                        'SR' => 'Suriname',
                        'SJ' => 'Svalbard & Jan Mayen',
                        'SE' => 'Sweden',
                        'CH' => 'Switzerland',
                        'SY' => 'Syria',
                        'TW' => 'Taiwan',
                        'TJ' => 'Tajikistan',
                        'TZ' => 'Tanzania',
                        'TH' => 'Thailand',
                        'TL' => 'Timor-Leste',
                        'TG' => 'Togo',
                        'TK' => 'Tokelau',
                        'TO' => 'Tonga',
                        'TT' => 'Trinidad & Tobago',
                        'TA' => 'Tristan da Cunha',
                        'TN' => 'Tunisia',
                        'TR' => 'Turkey',
                        'TM' => 'Turkmenistan',
                        'TC' => 'Turks & Caicos Islands',
                        'TV' => 'Tuvalu',
                        'UG' => 'Uganda',
                        'UA' => 'Ukraine',
                        'AE' => 'United Arab Emirates',
                        'GB' => 'United Kingdom',
                        'US' => 'United States',
                        'UY' => 'Uruguay',
                        'UM' => 'US Outlying Islands',
                        'VI' => 'US Virgin Islands',
                        'UZ' => 'Uzbekistan',
                        'VU' => 'Vanuatu',
                        'VA' => 'Vatican City',
                        'VE' => 'Venezuela',
                        'VN' => 'Vietnam',
                        'WF' => 'Wallis & Futuna',
                        'EH' => 'Western Sahara',
                        'YE' => 'Yemen',
                        'ZM' => 'Zambia',
                        'ZW' => 'Zimbabwe',
                    ),
                    'placeholder' => 'Select a country',
                    'default_value' => array(
                    ),
                    'allow_null' => 0,
                    'multiple' => 1,
                    'ui' => 1,
                    'return_format' => 'array',
                    'layout' => 'vertical',
                    'ajax' => 0,
                    'parent' => 'field_disclaimer_settings_country_disclaimers_group',
                ));

                acf_add_local_field(array(
                    'key' => 'field_disclaimer_settings_country_disclaimers_group_content',
                    'label' => 'Content',
                    'name' => 'disclaimer_settings_country_disclaimers_group_content',
                    'type' => 'wysiwyg',
                    'required' => 0,
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                    'delay' => 0,
                    'parent' => 'field_disclaimer_settings_country_disclaimers_group',
                ));

        acf_add_local_field(array(
            'key' => 'field_disclaimer_settings_show_user_type',
            'label' => 'Show user type field?',
            'name' => 'disclaimer_settings_show_user_type',
            'type' => 'true_false',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_disclaimer_settings_enable_disclaimer',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'default_value' => 0,
            'ui' => 1,
            'parent' => 'group_disclaimer_settings',
        ));

        acf_add_local_field(array(
            'key' => 'field_disclaimer_settings_user_types',
            'label' => 'User types',
            'name' => 'disclaimer_settings_user_types',
            'type' => 'repeater',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_disclaimer_settings_show_user_type',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => 'Add User Type',
            'rows_per_page' => 20,
            'sub_field' => array(),
            'parent' => 'group_disclaimer_settings',
        ));

            acf_add_local_field(array(
                'key' => 'field_disclaimer_settings_user_types_name',
                'label' => 'Name',
                'name' => 'disclaimer_settings_user_types_name',
                'type' => 'text',
                'required' => 1,
                'wrapper' => array(
                    'width' => '30',
                    'class' => '',
                    'id' => '',
                ),
                'parent' => 'field_disclaimer_settings_user_types',
            ));

            acf_add_local_field(array(
                'key'   => 'field_disclaimer_settings_user_types_selected_countries',
                'label' => 'Show this user on selected countries',
                'name'  => 'disclaimer_settings_user_types_selected_countries',
                'type'  => 'select',
                'required' => 0,
                'choices' => array(
                    'AF' => 'Afghanistan',
                    'AX' => 'Åland Islands',
                    'AL' => 'Albania',
                    'DZ' => 'Algeria',
                    'AS' => 'American Samoa',
                    'AD' => 'Andorra',
                    'AO' => 'Angola',
                    'AI' => 'Anguilla',
                    'AQ' => 'Antarctica',
                    'AG' => 'Antigua & Barbuda',
                    'AR' => 'Argentina',
                    'AM' => 'Armenia',
                    'AW' => 'Aruba',
                    'AC' => 'Ascension Island',
                    'AU' => 'Australia',
                    'AT' => 'Austria',
                    'AZ' => 'Azerbaijan',
                    'BS' => 'Bahamas',
                    'BH' => 'Bahrain',
                    'BD' => 'Bangladesh',
                    'BB' => 'Barbados',
                    'BY' => 'Belarus',
                    'BE' => 'Belgium',
                    'BZ' => 'Belize',
                    'BJ' => 'Benin',
                    'BM' => 'Bermuda',
                    'BT' => 'Bhutan',
                    'BO' => 'Bolivia',
                    'BA' => 'Bosnia & Herzegovina',
                    'BW' => 'Botswana',
                    'BR' => 'Brazil',
                    'IO' => 'British Indian Ocean Territory',
                    'VG' => 'British Virgin Islands',
                    'BN' => 'Brunei',
                    'BG' => 'Bulgaria',
                    'BF' => 'Burkina Faso',
                    'BI' => 'Burundi',
                    'KH' => 'Cambodia',
                    'CM' => 'Cameroon',
                    'CA' => 'Canada',
                    'IC' => 'Canary Islands',
                    'CV' => 'Cape Verde',
                    'BQ' => 'Caribbean Netherlands',
                    'KY' => 'Cayman Islands',
                    'CF' => 'Central African Republic',
                    'EA' => 'Ceuta & Melilla',
                    'TD' => 'Chad',
                    'CL' => 'Chile',
                    'CN' => 'China',
                    'CX' => 'Christmas Island',
                    'CC' => 'Cocos (Keeling) Islands',
                    'CO' => 'Colombia',
                    'KM' => 'Comoros',
                    'CG' => 'Congo - Brazzaville',
                    'CD' => 'Congo - Kinshasa',
                    'CK' => 'Cook Islands',
                    'CR' => 'Costa Rica',
                    'CI' => 'Côte d’Ivoire',
                    'HR' => 'Croatia',
                    'CU' => 'Cuba',
                    'CW' => 'Curaçao',
                    'CY' => 'Cyprus',
                    'CZ' => 'Czechia',
                    'DK' => 'Denmark',
                    'DG' => 'Diego Garcia',
                    'DJ' => 'Djibouti',
                    'DM' => 'Dominica',
                    'DO' => 'Dominican Republic',
                    'EC' => 'Ecuador',
                    'EG' => 'Egypt',
                    'SV' => 'El Salvador',
                    'GQ' => 'Equatorial Guinea',
                    'ER' => 'Eritrea',
                    'EE' => 'Estonia',
                    'SZ' => 'Eswatini',
                    'ET' => 'Ethiopia',
                    'FK' => 'Falkland Islands',
                    'FO' => 'Faroe Islands',
                    'FJ' => 'Fiji',
                    'FI' => 'Finland',
                    'FR' => 'France',
                    'GF' => 'French Guiana',
                    'PF' => 'French Polynesia',
                    'TF' => 'French Southern Territories',
                    'GA' => 'Gabon',
                    'GM' => 'Gambia',
                    'GE' => 'Georgia',
                    'DE' => 'Germany',
                    'GH' => 'Ghana',
                    'GI' => 'Gibraltar',
                    'GR' => 'Greece',
                    'GL' => 'Greenland',
                    'GD' => 'Grenada',
                    'GP' => 'Guadeloupe',
                    'GU' => 'Guam',
                    'GT' => 'Guatemala',
                    'GG' => 'Guernsey',
                    'GN' => 'Guinea',
                    'GW' => 'Guinea-Bissau',
                    'GY' => 'Guyana',
                    'HT' => 'Haiti',
                    'HN' => 'Honduras',
                    'HK' => 'Hong Kong SAR China',
                    'HU' => 'Hungary',
                    'IS' => 'Iceland',
                    'IN' => 'India',
                    'ID' => 'Indonesia',
                    'IR' => 'Iran',
                    'IQ' => 'Iraq',
                    'IE' => 'Ireland',
                    'IM' => 'Isle of Man',
                    'IL' => 'Israel',
                    'IT' => 'Italy',
                    'JM' => 'Jamaica',
                    'JP' => 'Japan',
                    'JE' => 'Jersey',
                    'JO' => 'Jordan',
                    'KZ' => 'Kazakhstan',
                    'KE' => 'Kenya',
                    'KI' => 'Kiribati',
                    'XK' => 'Kosovo',
                    'KW' => 'Kuwait',
                    'KG' => 'Kyrgyzstan',
                    'LA' => 'Laos',
                    'LV' => 'Latvia',
                    'LB' => 'Lebanon',
                    'LS' => 'Lesotho',
                    'LR' => 'Liberia',
                    'LY' => 'Libya',
                    'LI' => 'Liechtenstein',
                    'LT' => 'Lithuania',
                    'LU' => 'Luxembourg',
                    'MO' => 'Macao SAR China',
                    'MG' => 'Madagascar',
                    'MW' => 'Malawi',
                    'MY' => 'Malaysia',
                    'MV' => 'Maldives',
                    'ML' => 'Mali',
                    'MT' => 'Malta',
                    'MH' => 'Marshall Islands',
                    'MQ' => 'Martinique',
                    'MR' => 'Mauritania',
                    'MU' => 'Mauritius',
                    'YT' => 'Mayotte',
                    'MX' => 'Mexico',
                    'FM' => 'Micronesia',
                    'MD' => 'Moldova',
                    'MC' => 'Monaco',
                    'MN' => 'Mongolia',
                    'ME' => 'Montenegro',
                    'MS' => 'Montserrat',
                    'MA' => 'Morocco',
                    'MZ' => 'Mozambique',
                    'MM' => 'Myanmar (Burma)',
                    'NA' => 'Namibia',
                    'NR' => 'Nauru',
                    'NP' => 'Nepal',
                    'NL' => 'Netherlands',
                    'NC' => 'New Caledonia',
                    'NZ' => 'New Zealand',
                    'NI' => 'Nicaragua',
                    'NE' => 'Niger',
                    'NG' => 'Nigeria',
                    'NU' => 'Niue',
                    'NF' => 'Norfolk Island',
                    'KP' => 'North Korea',
                    'MK' => 'North Macedonia',
                    'MP' => 'Northern Mariana Islands',
                    'NO' => 'Norway',
                    'OM' => 'Oman',
                    'PK' => 'Pakistan',
                    'PW' => 'Palau',
                    'PS' => 'Palestinian Territories',
                    'PA' => 'Panama',
                    'PG' => 'Papua New Guinea',
                    'PY' => 'Paraguay',
                    'PE' => 'Peru',
                    'PH' => 'Philippines',
                    'PN' => 'Pitcairn Islands',
                    'PL' => 'Poland',
                    'PT' => 'Portugal',
                    'XA' => 'Pseudo-Accents',
                    'XB' => 'Pseudo-Bidi',
                    'PR' => 'Puerto Rico',
                    'QA' => 'Qatar',
                    'RE' => 'Réunion',
                    'RO' => 'Romania',
                    'RU' => 'Russia',
                    'RW' => 'Rwanda',
                    'WS' => 'Samoa',
                    'SM' => 'San Marino',
                    'ST' => 'São Tomé & Príncipe',
                    'SA' => 'Saudi Arabia',
                    'SN' => 'Senegal',
                    'RS' => 'Serbia',
                    'SC' => 'Seychelles',
                    'SL' => 'Sierra Leone',
                    'SG' => 'Singapore',
                    'SX' => 'Sint Maarten',
                    'SK' => 'Slovakia',
                    'SI' => 'Slovenia',
                    'SB' => 'Solomon Islands',
                    'SO' => 'Somalia',
                    'ZA' => 'South Africa',
                    'GS' => 'South Georgia & South Sandwich Islands',
                    'KR' => 'South Korea',
                    'SS' => 'South Sudan',
                    'ES' => 'Spain',
                    'LK' => 'Sri Lanka',
                    'BL' => 'St Barthélemy',
                    'SH' => 'St Helena',
                    'KN' => 'St Kitts & Nevis',
                    'LC' => 'St Lucia',
                    'MF' => 'St Martin',
                    'PM' => 'St Pierre & Miquelon',
                    'VC' => 'St Vincent & Grenadines',
                    'SD' => 'Sudan',
                    'SR' => 'Suriname',
                    'SJ' => 'Svalbard & Jan Mayen',
                    'SE' => 'Sweden',
                    'CH' => 'Switzerland',
                    'SY' => 'Syria',
                    'TW' => 'Taiwan',
                    'TJ' => 'Tajikistan',
                    'TZ' => 'Tanzania',
                    'TH' => 'Thailand',
                    'TL' => 'Timor-Leste',
                    'TG' => 'Togo',
                    'TK' => 'Tokelau',
                    'TO' => 'Tonga',
                    'TT' => 'Trinidad & Tobago',
                    'TA' => 'Tristan da Cunha',
                    'TN' => 'Tunisia',
                    'TR' => 'Turkey',
                    'TM' => 'Turkmenistan',
                    'TC' => 'Turks & Caicos Islands',
                    'TV' => 'Tuvalu',
                    'UG' => 'Uganda',
                    'UA' => 'Ukraine',
                    'AE' => 'United Arab Emirates',
                    'GB' => 'United Kingdom',
                    'US' => 'United States',
                    'UY' => 'Uruguay',
                    'UM' => 'US Outlying Islands',
                    'VI' => 'US Virgin Islands',
                    'UZ' => 'Uzbekistan',
                    'VU' => 'Vanuatu',
                    'VA' => 'Vatican City',
                    'VE' => 'Venezuela',
                    'VN' => 'Vietnam',
                    'WF' => 'Wallis & Futuna',
                    'EH' => 'Western Sahara',
                    'YE' => 'Yemen',
                    'ZM' => 'Zambia',
                    'ZW' => 'Zimbabwe',
                ),
                'placeholder' => 'Select countries',
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 1,
                'ui' => 1,
                'return_format' => 'array',
                'layout' => 'vertical',
                'ajax' => 0,
                'parent' => 'field_disclaimer_settings_user_types',
            ));

            acf_add_local_field(array(
                'key' => 'field_disclaimer_settings_user_types_allow',
                'label' => 'Allow this user?',
                'name' => 'disclaimer_settings_user_types_allow',
                'type' => 'true_false',
                'required' => 0,
                'default_value' => 1,
                'ui' => 1,
                'wrapper' => array(
                    'width' => '10',
                    'class' => '',
                    'id' => '',
                ),
                'parent' => 'field_disclaimer_settings_user_types',
            ));

        acf_add_local_field(array(
            'key' => 'field_disclaimer_settings_deny_page',
            'label' => 'Deny page',
            'name' => 'disclaimer_settings_deny_page',
            'type' => 'post_object',
            'required' => 1,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_disclaimer_settings_enable_disclaimer',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'post_type' => array(
                0 => 'page',
            ),
            'taxonomy' => '',
            'allow_null' => 0,
            'multiple' => 0,
            'return_format' => 'id',
            'ui' => 1,
            'parent' => 'group_disclaimer_settings',
        ));

        // permission setting
        acf_add_local_field_group(array(
            'key' => 'group_disclaimer_posts_settings',
            'title' => 'Disclaimer permission setting',
            'menu_order' => 0,
            'position' => 'side',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'all',
                    ),
                ),
            ),
        ));

        acf_add_local_field(array(
            'key'   => 'field_disclaimer_posts_settings_countries_allow',
            'label' => 'Countries to allow to see this page?',
            'name'  => 'disclaimer_posts_settings_countries_allow',
            'type'  => 'select',
            'required' => 0,
            'choices' => array(
                'AF' => 'Afghanistan',
                'AX' => 'Åland Islands',
                'AL' => 'Albania',
                'DZ' => 'Algeria',
                'AS' => 'American Samoa',
                'AD' => 'Andorra',
                'AO' => 'Angola',
                'AI' => 'Anguilla',
                'AQ' => 'Antarctica',
                'AG' => 'Antigua & Barbuda',
                'AR' => 'Argentina',
                'AM' => 'Armenia',
                'AW' => 'Aruba',
                'AC' => 'Ascension Island',
                'AU' => 'Australia',
                'AT' => 'Austria',
                'AZ' => 'Azerbaijan',
                'BS' => 'Bahamas',
                'BH' => 'Bahrain',
                'BD' => 'Bangladesh',
                'BB' => 'Barbados',
                'BY' => 'Belarus',
                'BE' => 'Belgium',
                'BZ' => 'Belize',
                'BJ' => 'Benin',
                'BM' => 'Bermuda',
                'BT' => 'Bhutan',
                'BO' => 'Bolivia',
                'BA' => 'Bosnia & Herzegovina',
                'BW' => 'Botswana',
                'BR' => 'Brazil',
                'IO' => 'British Indian Ocean Territory',
                'VG' => 'British Virgin Islands',
                'BN' => 'Brunei',
                'BG' => 'Bulgaria',
                'BF' => 'Burkina Faso',
                'BI' => 'Burundi',
                'KH' => 'Cambodia',
                'CM' => 'Cameroon',
                'CA' => 'Canada',
                'IC' => 'Canary Islands',
                'CV' => 'Cape Verde',
                'BQ' => 'Caribbean Netherlands',
                'KY' => 'Cayman Islands',
                'CF' => 'Central African Republic',
                'EA' => 'Ceuta & Melilla',
                'TD' => 'Chad',
                'CL' => 'Chile',
                'CN' => 'China',
                'CX' => 'Christmas Island',
                'CC' => 'Cocos (Keeling) Islands',
                'CO' => 'Colombia',
                'KM' => 'Comoros',
                'CG' => 'Congo - Brazzaville',
                'CD' => 'Congo - Kinshasa',
                'CK' => 'Cook Islands',
                'CR' => 'Costa Rica',
                'CI' => 'Côte d’Ivoire',
                'HR' => 'Croatia',
                'CU' => 'Cuba',
                'CW' => 'Curaçao',
                'CY' => 'Cyprus',
                'CZ' => 'Czechia',
                'DK' => 'Denmark',
                'DG' => 'Diego Garcia',
                'DJ' => 'Djibouti',
                'DM' => 'Dominica',
                'DO' => 'Dominican Republic',
                'EC' => 'Ecuador',
                'EG' => 'Egypt',
                'SV' => 'El Salvador',
                'GQ' => 'Equatorial Guinea',
                'ER' => 'Eritrea',
                'EE' => 'Estonia',
                'SZ' => 'Eswatini',
                'ET' => 'Ethiopia',
                'FK' => 'Falkland Islands',
                'FO' => 'Faroe Islands',
                'FJ' => 'Fiji',
                'FI' => 'Finland',
                'FR' => 'France',
                'GF' => 'French Guiana',
                'PF' => 'French Polynesia',
                'TF' => 'French Southern Territories',
                'GA' => 'Gabon',
                'GM' => 'Gambia',
                'GE' => 'Georgia',
                'DE' => 'Germany',
                'GH' => 'Ghana',
                'GI' => 'Gibraltar',
                'GR' => 'Greece',
                'GL' => 'Greenland',
                'GD' => 'Grenada',
                'GP' => 'Guadeloupe',
                'GU' => 'Guam',
                'GT' => 'Guatemala',
                'GG' => 'Guernsey',
                'GN' => 'Guinea',
                'GW' => 'Guinea-Bissau',
                'GY' => 'Guyana',
                'HT' => 'Haiti',
                'HN' => 'Honduras',
                'HK' => 'Hong Kong SAR China',
                'HU' => 'Hungary',
                'IS' => 'Iceland',
                'IN' => 'India',
                'ID' => 'Indonesia',
                'IR' => 'Iran',
                'IQ' => 'Iraq',
                'IE' => 'Ireland',
                'IM' => 'Isle of Man',
                'IL' => 'Israel',
                'IT' => 'Italy',
                'JM' => 'Jamaica',
                'JP' => 'Japan',
                'JE' => 'Jersey',
                'JO' => 'Jordan',
                'KZ' => 'Kazakhstan',
                'KE' => 'Kenya',
                'KI' => 'Kiribati',
                'XK' => 'Kosovo',
                'KW' => 'Kuwait',
                'KG' => 'Kyrgyzstan',
                'LA' => 'Laos',
                'LV' => 'Latvia',
                'LB' => 'Lebanon',
                'LS' => 'Lesotho',
                'LR' => 'Liberia',
                'LY' => 'Libya',
                'LI' => 'Liechtenstein',
                'LT' => 'Lithuania',
                'LU' => 'Luxembourg',
                'MO' => 'Macao SAR China',
                'MG' => 'Madagascar',
                'MW' => 'Malawi',
                'MY' => 'Malaysia',
                'MV' => 'Maldives',
                'ML' => 'Mali',
                'MT' => 'Malta',
                'MH' => 'Marshall Islands',
                'MQ' => 'Martinique',
                'MR' => 'Mauritania',
                'MU' => 'Mauritius',
                'YT' => 'Mayotte',
                'MX' => 'Mexico',
                'FM' => 'Micronesia',
                'MD' => 'Moldova',
                'MC' => 'Monaco',
                'MN' => 'Mongolia',
                'ME' => 'Montenegro',
                'MS' => 'Montserrat',
                'MA' => 'Morocco',
                'MZ' => 'Mozambique',
                'MM' => 'Myanmar (Burma)',
                'NA' => 'Namibia',
                'NR' => 'Nauru',
                'NP' => 'Nepal',
                'NL' => 'Netherlands',
                'NC' => 'New Caledonia',
                'NZ' => 'New Zealand',
                'NI' => 'Nicaragua',
                'NE' => 'Niger',
                'NG' => 'Nigeria',
                'NU' => 'Niue',
                'NF' => 'Norfolk Island',
                'KP' => 'North Korea',
                'MK' => 'North Macedonia',
                'MP' => 'Northern Mariana Islands',
                'NO' => 'Norway',
                'OM' => 'Oman',
                'PK' => 'Pakistan',
                'PW' => 'Palau',
                'PS' => 'Palestinian Territories',
                'PA' => 'Panama',
                'PG' => 'Papua New Guinea',
                'PY' => 'Paraguay',
                'PE' => 'Peru',
                'PH' => 'Philippines',
                'PN' => 'Pitcairn Islands',
                'PL' => 'Poland',
                'PT' => 'Portugal',
                'XA' => 'Pseudo-Accents',
                'XB' => 'Pseudo-Bidi',
                'PR' => 'Puerto Rico',
                'QA' => 'Qatar',
                'RE' => 'Réunion',
                'RO' => 'Romania',
                'RU' => 'Russia',
                'RW' => 'Rwanda',
                'WS' => 'Samoa',
                'SM' => 'San Marino',
                'ST' => 'São Tomé & Príncipe',
                'SA' => 'Saudi Arabia',
                'SN' => 'Senegal',
                'RS' => 'Serbia',
                'SC' => 'Seychelles',
                'SL' => 'Sierra Leone',
                'SG' => 'Singapore',
                'SX' => 'Sint Maarten',
                'SK' => 'Slovakia',
                'SI' => 'Slovenia',
                'SB' => 'Solomon Islands',
                'SO' => 'Somalia',
                'ZA' => 'South Africa',
                'GS' => 'South Georgia & South Sandwich Islands',
                'KR' => 'South Korea',
                'SS' => 'South Sudan',
                'ES' => 'Spain',
                'LK' => 'Sri Lanka',
                'BL' => 'St Barthélemy',
                'SH' => 'St Helena',
                'KN' => 'St Kitts & Nevis',
                'LC' => 'St Lucia',
                'MF' => 'St Martin',
                'PM' => 'St Pierre & Miquelon',
                'VC' => 'St Vincent & Grenadines',
                'SD' => 'Sudan',
                'SR' => 'Suriname',
                'SJ' => 'Svalbard & Jan Mayen',
                'SE' => 'Sweden',
                'CH' => 'Switzerland',
                'SY' => 'Syria',
                'TW' => 'Taiwan',
                'TJ' => 'Tajikistan',
                'TZ' => 'Tanzania',
                'TH' => 'Thailand',
                'TL' => 'Timor-Leste',
                'TG' => 'Togo',
                'TK' => 'Tokelau',
                'TO' => 'Tonga',
                'TT' => 'Trinidad & Tobago',
                'TA' => 'Tristan da Cunha',
                'TN' => 'Tunisia',
                'TR' => 'Turkey',
                'TM' => 'Turkmenistan',
                'TC' => 'Turks & Caicos Islands',
                'TV' => 'Tuvalu',
                'UG' => 'Uganda',
                'UA' => 'Ukraine',
                'AE' => 'United Arab Emirates',
                'GB' => 'United Kingdom',
                'US' => 'United States',
                'UY' => 'Uruguay',
                'UM' => 'US Outlying Islands',
                'VI' => 'US Virgin Islands',
                'UZ' => 'Uzbekistan',
                'VU' => 'Vanuatu',
                'VA' => 'Vatican City',
                'VE' => 'Venezuela',
                'VN' => 'Vietnam',
                'WF' => 'Wallis & Futuna',
                'EH' => 'Western Sahara',
                'YE' => 'Yemen',
                'ZM' => 'Zambia',
                'ZW' => 'Zimbabwe',
            ),
            'placeholder' => 'Select countries',
            'default_value' => array(
            ),
            'allow_null' => 0,
            'multiple' => 1,
            'ui' => 1,
            'return_format' => 'array',
            'layout' => 'vertical',
            'ajax' => 0,
            'parent' => 'group_disclaimer_posts_settings',
        ));

        acf_add_local_field(array(
            'key'   => 'field_disclaimer_posts_settings_user_types_allow',
            'label' => 'User type to allow to see this page?',
            'name'  => 'disclaimer_posts_settings_user_types_allow',
            'type'  => 'checkbox',
            'required' => 0,
            'choices' => [],
            'default_value' => [],
            'layout' => 'vertical',
            'toggle' => 0,
            'return_format' => 'value',
            'parent' => 'group_disclaimer_posts_settings',
        ));

    }
}
